#sudo: required
#dist: trusty
language: python
node_js:
  - "6"
python:
  - "3.4"
  - "3.5"

cache:
  apt: true
  pip: true
  nvm: true
  npm: true

services:
  - postgresql

env:
  global:
    - DATABASE_URL=postgres://postgres@127.0.0.1:5432/postgres

# command to install dependencies
install:
  - nvm install 6
  - nvm use 6
  - npm install
  - pip install -r requirements.txt

# generate bundles
before_script:
  - npm run build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database django;' -U postgres
  - psql -c 'create database test_django;' -U postgres
  - python manage.py collectstatic --noinput

# command to run tests
script:
  # run server tests
  - python manage.py test
  # run frontend tests
  - npm test -- --browsers PhantomJS,Firefox
