# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_featurerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='ticket_url',
            field=models.URLField(blank=True, default='', verbose_name='Ticket URL'),
        ),
        migrations.AlterUniqueTogether(
            name='featurerequest',
            unique_together=set([('client', 'client_priority')]),
        ),
    ]
